fixed issue Misplaced pagination buttons in Users page #2683
apinf/meteor-accounts-admin-ui-bootstrap-3 pull request #4
Opened 2017-08-29 10:25 UTC by saransh-dev

#Fixed issue [#2683](https://github.com/apinf/platform/issues/2683)

### changes:-
client/accounts_admin.html
style/style.css

Closes: [#2683](https://github.com/apinf/platform/issues/2683)

2017-08-29 14:44 UTC, marla-singer requested changes
Re-think about style. Keep the styling as simple as possible. After remaking remove useless styles

2017-08-29 14:44 UTC, marla-singer commented on client/accounts_admin.html
> +    {{> defaultBootstrapPaginator pagination=templatePagination limit=10 containerClass=""}}
Add class `text-center` as value of attribute `containerClass` and remove upper `div` block. 
It allows the same design that you made but using a tool of pagination button

2017-08-29 14:44 UTC, marla-singer commented on style/style.css
> +    float: none;
Remove `float:left` from `.items-on-page` rule.

2017-08-29 14:44 UTC, marla-singer commented on style/style.css
> +    margin-top: -28px;
I found that you used it to place pagination button and text in one line. Really bad and dirty hack.

I propose not keeping these items in one line. Text about a count of users set under the table and pagination button will have a place in a new line.
![joxi_screenshot_1504017774932](https://user-images.githubusercontent.com/20643403/29827033-8a8ad2b6-8ce1-11e7-99c5-2b039b5203f4.png)

2017-08-30 15:50 UTC, saransh-dev commented
@marla-singer  I have removed extra div and changed the code as you suggested. Please review.

2017-08-31 14:26 UTC, marla-singer approved these changes

2017-08-31 14:26 UTC, merged